# Generated by Django 3.0.8 on 2020-08-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='태그명')),
                ('registered_dttm', models.DateTimeField(auto_now=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '페스트컴퍼스 태그',
                'verbose_name_plural': '페스트컴퍼스 태그',
                'db_table': 'fastcampus_tag',
            },
        ),
    ]
