# Generated by Django 3.0.8 on 2020-08-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20200804_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='test@gamil.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
